Wörterliste = [
    "Algorithmus",
    "API",
    "Cloud",
    "Daten",
    "Debugging",
    "Frontend",
    "Backend",
    "Server",
    "Datenbank",
    "Virtualisierung",
    "Container",
    "DevOps",
    "Verschlüsselung",
    "Skripting",
    "Middleware",
    "Architektur",
    "Benutzeroberfläche",
    "Framework",
    "Microservices",
    "Repository",
    "SSH",
    "VPN",
    "Load",
    "Balancer",
    "CI",
    "Docker",
    "Kubernetes",
    "SQL",
    "NoSQL",
    "Firewall",
    "DNS",
    "HTTP",
    "HTTPS",
    "JSON",
    "XML",
    "Gateway",
    "HTTP Proxy",
    "SSL",
    "TLS",
    "IPv4",
    "IPv6",
    "LAN",
    "WAN",
    "VLAN",
    "IPsec",
    "Gateway",
    "Switch",
    "Router",
    "Token",
    "Zertifikat",
    "Authentifizierung",
    "Autorisierung",
    "OAuth",
    "Sitzung",
    "Cookie",
    "Websocket",
    "Nginx",
    "Apache",
    "BGP",
    "NAT",
    "Subnetz",
    "CIDR",
    "Lastverteilung",
    "Backup",
    "Wiederherstellung",
    "RAID",
    "SSD",
    "HDD",
    "Bandbreite",
    "Durchsatz",
    "Latenz",
    "Ping",
    "Traceroute",
    "QoS",
    "DNSSEC",
    "CDN",
    "Cache",
    "Trefferquote",
    "DDoS",
    "Spoofing",
    "Phishing",
    "Malware",
    "Ransomware",
    "Virus",
    "Trojaner",
    "Wurm",
    "Botnetz",
    "Honeypot",
    "SIEM",
    "IDS",
    "IPS",
    "SOC",
    "Penetrationstest",
    "Schwachstelle",
    "Exploit",
    "Patch"
]

man = ["\n  +---+\n  |   |\n      |\n      |\n      |\n      |\n=========", "\n  +---+\n  |   |\n  O   |\n      |\n      |\n      |\n=========", "\n  +---+\n  |   |\n  O   |\n  |   |\n      |\n      |\n=========", "\n  +---+\n  |   |\n  O   |\n /|   |\n      |\n      |\n=========", "\n  +---+\n  |   |\n  O   |\n /|\\  |\n      |\n      |\n=========", "\n  +---+\n  |   |\n  O   |\n /|\\  |\n /    |\n      |\n=========", "\n  +---+\n  |   |\n  O   |\n /|\\  |\n / \\  |\n      |\n=========="]

death = "⠀⠀⠀⠀⠀⠀⠀⠀⢀⣀⣤⣤⠴⠶⠶⠶⠶⠶⠶⠶⠶⢤⣤⣀⡀⠀⠀⠀⠀⠀⠀⠀⠀\n⠀⠀⠀⠀⢀⣤⠶⠛⠉⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠉⠛⠶⣤⡀⠀⠀⠀⠀\n⠀⠀⢀⡴⠛⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠛⢷⡄⠀⠀\n⠀⣰⠟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠹⣦⠀\n⢰⠏⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠹⣧\n⣿⠀⠀⣤⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⡄⠀⢹⡄\n⡏⠀⢰⡏⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⠀⢸⡇\n⣿⠀⠘⣇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⡟⠀⢸⡇\n⢹⡆⠀⢹⡆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣼⠃⠀⣾⠀\n⠈⢷⡀⢸⡇⠀⢀⣠⣤⣶⣶⣶⣤⡀⠀⠀⠀⠀⠀⢀⣠⣶⣶⣶⣶⣤⣄⠀⠀⣿⠀⣼⠃⠀\n⠀⠈⢷⣼⠃⠀⣿⣿⣿⣿⣿⣿⣿⣿⡄⠀⠀⠀⠀⣾⣿⣿⣿⣿⣿⣿⣿⡇⠀⢸⡾⠃⠀⠀\n⠀⠀⠈⣿⠀⠀⢿⣿⣿⣿⣿⣿⣿⣿⠁⠀⠀⠀⠀⢹⣿⣿⣿⣿⣿⣿⣿⠃⠀⢸⡇⠀⠀⠀\n⠀⠀⠀⣿⠀⠀⠘⢿⣿⣿⣿⣿⡿⠃⠀⢠⠀⣄⠀⠀⠙⢿⣿⣿⣿⡿⠏⠀⠀⢘⡇⠀⠀⠀\n⠀⠀⠀⢻⡄⠀⠀⠀⠈⠉⠉⠀⠀⠀⣴⣿⠀⣿⣷⠀⠀⠀⠀⠉⠁⠀⠀⠀⠀⢸⡇⠀⠀⠀\n⠀⠀⠀⠈⠻⣄⡀⠀⠀⠀⠀⠀⠀⢠⣿⣿⠀⣿⣿⣇⠀⠀⠀⠀⠀⠀⠀⢀⣴⠟⠀⠀⠀⠀\n⠀⠀⠀⠀⠀⠘⣟⠳⣦⡀⠀⠀⠀⠸⣿⡿⠀⢻⣿⡟⠀⠀⠀⠀⣤⡾⢻⡏⠁⠀⠀⠀⠀⠀\n⠀⠀⠀⠀⠀⠀⢻⡄⢻⠻⣆⠀⠀⠀⠈⠀⠀⠀⠈⠀⠀⠀⢀⡾⢻⠁⢸⠁⠀⠀⠀⠀⠀⠀\n⠀⠀⠀⠀⠀⠀⢸⡇⠀⡆⢹⠒⡦⢤⠤⡤⢤⢤⡤⣤⠤⡔⡿⢁⡇⠀⡿⠀⠀⠀⠀⠀⠀⠀\n⠀⠀⠀⠀⠀⠀⠘⡇⠀⢣⢸⠦⣧⣼⣀⡇⢸⢀⣇⣸⣠⡷⢇⢸⠀⠀⡇⠀⠀⠀⠀⠀⠀⠀\n⠀⠀⠀⠀⠀⠀⠀⣷⠀⠈⠺⣄⣇⢸⠉⡏⢹⠉⡏⢹⢀⣧⠾⠋⠀⢠⡇⠀⠀⠀⠀⠀⠀⠀\n⠀⠀⠀⠀⠀⠀⠀⠻⣆⠀⠀⠀⠈⠉⠙⠓⠚⠚⠋⠉⠁⠀⠀⠀⢀⡾⠁⠀⠀⠀⠀⠀⠀⠀\n⠀⠀⠀⠀⠀⠀⠀⠀⠙⢷⣄⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⡴⠛⠁⠀⠀⠀⠀⠀⠀⠀⠀\n⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠙⠳⠶⠦⣤⣤⣤⡤⠶⠞⠋⠁⠀⠀⠀⠀"

startscreen="|---Welcome to Python Hangman---|\n|            Made By            |\n|                               |\n|   #######   #     #    ###    |\n|      #      ##   ##   #       |\n|      #      # # # #   #       |\n|      #      #  #  #    ###    |\n|-------------------------------|"

win = """$$\\     $$\\                         $$\\      $$\\ $$\\           \n\\$$\\   $$  |                        $$ | $\\  $$ |\\__|          \n \\$$\\ $$  /$$$$$$\\  $$\\   $$\\       $$ |$$$\\ $$ |$$\\ $$$$$$$\\  \n  \\$$$$  /$$  __$$\\ $$ |  $$ |      $$ $$ $$\\$$ |$$ |$$  __$$\\ \n   \\$$  / $$ /  $$ |$$ |  $$ |      $$$$  _$$$$ |$$ |$$ |  $$ | \n    $$ |  $$ |  $$ |$$ |  $$ |      $$$  / \\$$$ |$$ |$$ |  $$ | \n    $$ |  \\$$$$$$  |\\$$$$$$  |      $$  /   \\$$ |$$ |$$ |  $$ | \n    \\__|   \\______/  \\______/       \\__/     \\__|\\__|\\__|  \\__|"""

dragon = """   (  )   /\   _                 (\n    \ |  (  \ ( \\                 )                      _____\n  \\  \\ \\  `  `   )               (  ___                 / _   \\\n (_`    \\+   . x  (               \\/   \\____-----------/ (o)   \\_ \n- .-               \\+  ;          (  O                           \\____\n(__                +- .( -'.- <.   \\_____________  `              \\  / \n(_____            ._._: <_ - <- _- _  VVVVVVV VV V\\                \\/\n  .    /./.+-  . .- /  +--  - .    (--_AAAAAAA__A_/                |\n  (__ ' /x  / x _/ (                \\______________//_              \\_______\n , x / ( '  . / .  /                                  \\___'          \\     /\n    /  /  _/ /    +                                       |           \\   /\n   '  (__/                                               /              \\/\n                                                       /                  \\ """